/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#00476e',
        surface: '#f8f9ff',
        tertiary: '#00573b',
        'tertiary-fixed-dim': '#68dba9',
        'on-primary-container': '#cbe4ff',
        'on-background': '#0b1c30',
        'on-surface': '#0b1c30',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'secondary-container': '#5bb8fe',
        'on-secondary-fixed': '#001d31',
        'secondary-fixed-dim': '#93ccff',
        'inverse-primary': '#94ccff',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'error-container': '#ffdad6',
        outline: '#707881',
        'on-primary-fixed': '#001d32',
        'secondary-fixed': '#cce5ff',
        'on-tertiary-fixed': '#002114',
        'primary-fixed': '#cde5ff',
        'on-primary-fixed-variant': '#004b74',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-secondary-fixed-variant': '#004b73',
        'surface-container-highest': '#d3e4fe',
        'inverse-surface': '#213145',
        secondary: '#006398',
        error: '#ba1a1a',
        'primary-fixed-dim': '#94ccff',
        'surface-container': '#e5eeff',
        'on-tertiary-container': '#83f7c2',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'tertiary-container': '#00724f',
        'outline-variant': '#c0c7d1',
        primary: '#00507d',
        'on-tertiary-fixed-variant': '#005137',
        'primary-container': '#0369a1',
        'tertiary-fixed': '#85f8c4',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#006399',
        'on-surface-variant': '#40474f',
        'inverse-on-surface': '#eaf1ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xl': '2.5rem',
        margin: '2rem',
        'gutter-mobile': '0.75rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Be Vietnam Pro'],
        'label-md': ['Be Vietnam Pro'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
        'headline-lg': ['Be Vietnam Pro'],
        'body-md': ['Inter'],
        display: ['Be Vietnam Pro'],
        'headline-sm': ['Be Vietnam Pro'],
        'headline-md': ['Be Vietnam Pro'],
        'label-lg': ['Be Vietnam Pro'],
        'label-sm': ['Be Vietnam Pro'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '26px',
          { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        display: [
          '44px',
          { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '700' },
        ],
        'headline-sm': [
          '18px',
          { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' },
        ],
        'label-lg': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' },
        ],
        'label-sm': [
          '10px',
          { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [],
}
